export const bn = {
  sidebar: {
    admin_dashboard: "অ্যাডমিন ড্যাশবোর্ড", dashboard: "ড্যাশবোর্ড", shg_members: "এসএইচজি সদস্য", loans_approvals: "ঋণ ও অনুমোদন", reports: "রিপোর্ট ও বিশ্লেষণ", transactions: "লেনদেন", settings: "সেটিংস", monthly_round: "মাসিক রাউন্ড", log_activity: "কার্যকলাপ লগ করুন", logout: "লগআউট", ledger: "আমার খতিয়ান", goals: "সঞ্চয় লক্ষ্য", loans: "ঋণ", learning: "আর্থিক স্বাক্ষরতা", group: "গ্রুপ ডিরেক্টরি", messages: "বার্তা", achievements: "অর্জন", profile: "প্রোফাইল"
  },
  common: {
    loading: "লোড হচ্ছে...", save: "সংরক্ষণ করুন", cancel: "বাতিল করুন", submit: "জমা দিন", verify: "যাচাই করুন", approve: "অনুমোদন করুন", reject: "প্রত্যাখ্যান করুন", amount: "পরিমাণ", status: "অবস্থা", date: "তারিখ", member: "সদস্য", mode: "মোড", description: "বিবরণ", action: "পদক্ষেপ", yes: "হ্যাঁ", no: "না", edit: "সম্পাদনা", delete: "মুছুন", view: "দেখুন", close: "বন্ধ করুন", search: "অনুসন্ধান", all: "সব", total: "মোট",
  },
  dashboard: {
    title: "ড্যাশবোর্ড", subtitle: "এসএইচজি পারফরম্যান্স মেট্রিক্স", total_members: "মোট সদস্য", this_month: "+৫ এই মাসে", total_savings: "মোট সঞ্চয়", vs_last_month: "গত মাসের তুলনায় +১২%", active_loans: "সক্রিয় ঋণ", repayments: "-৮% পরিশোধ", avg_trust_score: "গড় ট্রাস্ট স্কোর", points_diff: "+২.৩ পয়েন্ট", monthly_financial_activity: "মাসিক আর্থিক ক্রিয়াকলাপ", desc_monthly_activity: "সঞ্চয়, ঋণ বিতরণ এবং পরিশোধ", savings: "সঞ্চয়", loans_disbursed: "ঋণ বিতরণ", repayments_chart: "ঋণ পরিশোধ", trust_score_distribution: "ট্রাস্ট স্কোর বিতরণ", desc_trust_distribution: "স্কোর পরিসীমা অনুসারে সদস্য", members_count: "সদস্য", loan_repayment_status: "ঋণ পরিশোধের অবস্থা", desc_loan_repayment: "সময়মতো বনাম দেরি বনাম ডিফল্ট (%)", on_time: "সময়মতো", late: "দেরি", defaulted: "ডিফল্ট", meeting_attendance_trend: "সভায় উপস্থিতির প্রবণতা", desc_meeting_attendance: "প্রতি মাসে গড় উপস্থিতির শতাংশ", attendance_rate: "উপস্থিতির হার", quick_stats: "দ্রুত পরিসংখ্যান", this_month_stats: "এই মাসে", transactions_count: "লেনদেন", percent_vs_last_month: "+১৮% গত মাসের তুলনায়", repayment_rate: "পরিশোধের হার", excellent: "চমৎকার", group_health_score: "গ্রুপ স্বাস্থ্য স্কোর", top_performing: "শীর্ষ পারফর্মিং", member_since: "সদস্য হওয়ার তারিখ", monthly_contribution: "মাসিক অবদান", group_rank: "গ্রুপ র্যাঙ্ক", trust_score_trend: "ট্রাস্ট স্কোর প্রবণতা",
  },
  transactions: {
    title: "লেনদেন", no_transactions: "এখনও কোনও লেনদেন নেই", view_loan: "ঋণ দেখুন", verify_cash: "নগদ যাচাই করুন", verified: "যাচাইকৃত", pending: "অপেক্ষমান", online: "অনলাইন", cash: "নগদ", loan_details: "ঋণের বিবরণ", disbursed: "বিতরণ করা হয়েছে", loan_amount: "ঋণের পরিমাণ", remaining: "বাকি", repayment_progress: "পরিশোধের অগ্রগতি", emis_paid: "ইএমআই পরিশোধিত", monthly_emi: "মাসিক ইএমআই", next_due: "পরবর্তী প্রদেয়", all_paid: "সব পরিশোধিত", interest_rate: "সুদের হার", tenure: "মেয়াদ", months: "মাস", total_payable: "মোট প্রদেয়", amount_paid: "প্রদত্ত পরিমাণ", description: "বিবরণ", loan_not_found: "ঋণ পাওয়া যায়নি",
  },
  log_activity: {
    title: "কার্যকলাপ লগিং", subtitle: "আর্থিক লেনদেন এবং সভায় উপস্থিতি রেকর্ড করুন", fin_entry_title: "আর্থিক লেনদেন এন্ট্রি", fin_entry_desc: "সঞ্চয়, ঋণ বিতরণ বা পরিশোধ রেকর্ড করুন", member_name: "সদস্যের নাম", select_member: "সদস্য নির্বাচন করুন", amount_rupees: "পরিমাণ (₹)", transaction_type: "লেনদেনের ধরন", select_type: "ধরন নির্বাচন করুন", savings: "সঞ্চয়", loan_repayment: "ঋণ পরিশোধ", loan_disbursed: "ঋণ বিতরণ", record_fin_transaction: "লিনদেন রেকর্ড করুন", meeting_attendance: "সভায় উপস্থিতি", meeting_attendance_desc: "গ্রুপ মিটিংয়ের জন্য সদস্যের উপস্থিতি লগ করুন", meeting_date: "সাক্ষাতের তারিখ", meeting_topic: "সভার বিষয়", topic_placeholder: "যেমন, মাসিক পর্যালোচনা", present: "উপস্থিত", absent: "অনুপস্থিত", finalize_attendance: "উপস্থিতি লগ চূড়ান্ত করুন", recent_activity: "সাম্প্রতিক ক্রিয়াকলাপ", recent_activity_desc: "শেষ ৫টি রেকর্ড করা লেনদেন", no_recent: "কোনো সাম্প্রতিক পেমেন্ট নেই", monthly_round_payment: "মাসিক রাউন্ড পেমেন্ট", paid: "পরিশোধিত",
  },
  loan_approvals: {
    title: "ঋণের অনুমোদন", no_pending: "কোনও অপেক্ষমাণ ঋণের অনুরোধ নেই।", member_id: "সদস্য আইডি", amount: "পরিমাণ", tenure: "মেয়াদ", emi: "ইএমআই", purpose: "উদ্দেশ্য", approved: "অনুমোদিত", rejected: "প্রত্যাখ্যাত", approve_btn: "অনুমোদন করুন", reject_btn: "প্রত্যাখ্যান করুন",
  }
};

export const mr = {
  sidebar: {
    admin_dashboard: "अॅडमिन डॅशबोर्ड", dashboard: "डॅशबोर्ड", shg_members: "SHG सदस्य", loans_approvals: "कर्ज आणि मंजुरी", reports: "अहवाल आणि विश्लेषण", transactions: "व्यवहार", settings: "सेटिंग्ज", monthly_round: "मासिक राऊंड", log_activity: "अॅक्टिव्हिटी लॉग करा", logout: "लॉगआउट", ledger: "माझे लेजर", goals: "बचत ध्येये", loans: "कर्ज", learning: "आर्थिक साक्षरता", group: "गट निर्देशिका", messages: "संदेश", achievements: "उपलब्धी", profile: "प्रोफाइल"
  },
  common: {
    loading: "लोड होत आहे...", save: "सेव्ह करा", cancel: "रद्द करा", submit: "सबमिट करा", verify: "पडताळणी करा", approve: "मंजूर करा", reject: "नाकारा", amount: "रक्कम", status: "स्थिती", date: "तारीख", member: "सदस्य", mode: "मोड", description: "वर्णन", action: "कृती", yes: "होय", no: "नाही", edit: "संपादित करा", delete: "हटवा", view: "पहा", close: "बंद करा", search: "शोधा", all: "सर्व", total: "एकूण",
  },
  dashboard: {
    title: "डॅशबोर्ड", subtitle: "SHG कामगिरी मेट्रिक्स", total_members: "एकूण सदस्य", this_month: "या महिन्यात +5", total_savings: "एकूण बचत", vs_last_month: "गेल्या महिन्याच्या तुलनेत +12%", active_loans: "सक्रिय कर्ज", repayments: "-8% परतफेड", avg_trust_score: "सरासरी ट्र्स्ट स्कोअर", points_diff: "+2.3 गुण", monthly_financial_activity: "मासिक आर्थिक व्यवहार", desc_monthly_activity: "बचत, वितरित कर्ज आणि परतफेड", savings: "बचत", loans_disbursed: "वितरित कर्ज", repayments_chart: "परतफेड", trust_score_distribution: "ट्रस्ट स्कोअर वितरण", desc_trust_distribution: "स्कोअर श्रेणीनुसार सदस्य", members_count: "सदस्य", loan_repayment_status: "कर्ज परतफेड स्थिती", desc_loan_repayment: "वेळेवर वि. उशिरा वि. डिफॉल्ट (%)", on_time: "वेळेवर", late: "उशिरा", defaulted: "डिफॉल्ट", meeting_attendance_trend: "मीटिंग उपस्थिती कल", desc_meeting_attendance: "दरमहा सरासरी उपस्थिती टक्केवारी", attendance_rate: "उपस्थिती दर", quick_stats: "जलद आकडेवारी", this_month_stats: "या महिन्यात", transactions_count: "व्यवहार", percent_vs_last_month: "गेल्या महिन्याच्या तुलनेत +18%", repayment_rate: "परतफेड दर", excellent: "उत्कृष्ट", group_health_score: "गट आरोग्य स्कोअर", top_performing: "सर्वोत्तम कामगिरी", member_since: "सदस्य झाल्यापासून", monthly_contribution: "मासिक योगदान", group_rank: "गट रँक", trust_score_trend: "ट्रस्ट स्कोअर ट्रेंड",
  },
  transactions: {
    title: "व्यवहार", no_transactions: "अद्याप कोणतेही व्यवहार नाहीत", view_loan: "कर्ज पहा", verify_cash: "रोख पडताळणी करा", verified: "सत्यापित", pending: "प्रलंबित", online: "ऑनलाइन", cash: "रोख", loan_details: "कर्ज तपशील", disbursed: "वितरित केले", loan_amount: "कर्जाची रक्कम", remaining: "उर्वरित", repayment_progress: "परतफेड प्रगती", emis_paid: "ईएमआय भरले", monthly_emi: "मासिक ईएमआय", next_due: "पुढील देय", all_paid: "सर्व पेमेंट केले", interest_rate: "व्याज दर", tenure: "कालावधी", months: "महिने", total_payable: "एकूण देय", amount_paid: "भरलेली रक्कम", description: "वर्णन", loan_not_found: "कर्ज आढळले नाही",
  },
  log_activity: {
    title: "अॅक्टिव्हिटी लॉगिंग", subtitle: "आर्थिक व्यवहार आणि मीटिंग उपस्थिती नोंदवा", fin_entry_title: "आर्थिक व्यवहार नोंद", fin_entry_desc: "बचत, कर्ज वितरण किंवा परतफेड नोंदवा", member_name: "सदस्याचे नाव", select_member: "सदस्य निवडा", amount_rupees: "रक्कम (₹)", transaction_type: "व्यवहाराचा प्रकार", select_type: "प्रकार निवडा", savings: "बचत", loan_repayment: "कर्ज परतफेड", loan_disbursed: "कर्ज वितरित", record_fin_transaction: "व्यवहार नोंदवा", meeting_attendance: "मीटिंग उपस्थिती", meeting_attendance_desc: "गट मीटिंगसाठी सदस्य उपस्थिती लॉग करा", meeting_date: "मीटिंगची तारीख", meeting_topic: "मीटिंगचा विषय", topic_placeholder: "उदा. मासिक आढावा", present: "उपस्थित", absent: "अनुपस्थित", finalize_attendance: "उपस्थिती अंतिम करा", recent_activity: "अलीकडील अ‍ॅक्टिव्हिटी", recent_activity_desc: "शेवटचे 5 रेकॉर्ड केलेले व्यवहार", no_recent: "कोणतेही अलीकडील पेमेंट नाही", monthly_round_payment: "मासिक राऊंड पेमेंट", paid: "पेड",
  },
  loan_approvals: {
    title: "कर्ज मंजुरी", no_pending: "कोणत्याही प्रलंबित कर्ज विनंत्या नाहीत.", member_id: "सदस्य आयडी", amount: "रक्कम", tenure: "कालावधी", emi: "ईएमआय", purpose: "उद्देश", approved: "मंजूर", rejected: "नाकारले", approve_btn: "मंजूर करा", reject_btn: "नाकारा",
  }
};

export const te = {
  sidebar: {
    admin_dashboard: "అడ్మిన్ డాష్‌బోర్డ్", dashboard: "డాష్‌బోర్డ్", shg_members: "SHG సభ్యులు", loans_approvals: "రుణాలు & ఆమోదాలు", reports: "నివేదికలు & విశ్లేషణలు", transactions: "లావాదేవీలు", settings: "సెట్టింగులు", monthly_round: "నెలవారీ రౌండ్", log_activity: "యాక్టివిటీ లాగ్ చేయండి", logout: "లాగ్అవుట్", ledger: "నా లెడ్జర్", goals: "పొదుపు లక్ష్యాలు", loans: "రుణాలు", learning: "ఆ ఆర్థిక అక్షరాస్యత", group: "గ్రూప్ డైరెక్టరీ", messages: "సందేశాలు", achievements: "విజయాలు", profile: "ప్రొఫైల్"
  },
  common: {
    loading: "లోడ్ అవుతోంది...", save: "సేవ్ చేయండి", cancel: "రద్దు చేయండి", submit: "సమర్పించండి", verify: "ధృవీకరించండి", approve: "ఆమోదించండి", reject: "తిరస్కరించండి", amount: "మొత్తం", status: "స్థితి", date: "తేదీ", member: "సభ్యుడు", mode: "మోడ్", description: "వివరణ", action: "చర్య", yes: "అవును", no: "కాదు", edit: "సవరించండి", delete: "తొలగించండి", view: "చూడండి", close: "మూసివేయండి", search: "శోధించండి", all: "అన్నీ", total: "మొత్తం",
  },
  dashboard: {
    title: "డాష్‌బోర్డ్", subtitle: "SHG పనితీరు కొలమానాలు", total_members: "మొత్తం సభ్యులు", this_month: "ఈ నెల +5", total_savings: "మొత్తం పొదుపు", vs_last_month: "గత నెలతో పోలిస్తే +12%", active_loans: "క్రియాశీల రుణాలు", repayments: "-8% తిరిగి చెల్లింపులు", avg_trust_score: "సగటు ట్రస్ట్ స్కోర్", points_diff: "+2.3 పాయింట్లు", monthly_financial_activity: "నెలవారీ ఆర్థిక కార్యకలాపాలు", desc_monthly_activity: "పొదుపు, రుణాలు మరియు చెల్లింపులు", savings: "పొదుపు", loans_disbursed: "రుణాలు పంపిణీ చేయబడ్డాయి", repayments_chart: "తిరిగి చెల్లింపులు", trust_score_distribution: "ట్రస్ట్ స్కోర్ పంపిణీ", desc_trust_distribution: "స్కోర్ పరిధి వారీగా సభ్యుల పంపిణీ", members_count: "సభ్యులు", loan_repayment_status: "రుణ చెల్లింపు స్థితి", desc_loan_repayment: "ఆలస్యం vs డిఫాల్ట్ (%)", on_time: "సమయానికి", late: "ఆలస్యం", defaulted: "డిఫాల్ట్", meeting_attendance_trend: "హాజరు ట్రెండ్", desc_meeting_attendance: "నెలకు సగటు హాజరు శాతం", attendance_rate: "హాజరు రేటు", quick_stats: "త్వరిత గణాంకాలు", this_month_stats: "ఈ నెల", transactions_count: "లావాదేవీలు", percent_vs_last_month: "+18% గత నెలతో పోలిస్తే", repayment_rate: "చెల్లింపు రేటు", excellent: "అద్భుతమైన", group_health_score: "గ్రూప్ హెల్త్ స్కోర్", top_performing: "అత్యుత్తమ పనితీరు", member_since: "సభ్యత్వం ప్రారంభం", monthly_contribution: "నెలవారీ సహకారం", group_rank: "గ్రూప్ ర్యాంక్", trust_score_trend: "ట్రస్ట్ స్కోర్ ట్రెండ్",
  },
  transactions: {
    title: "లావాదేవీలు", no_transactions: "ఇంకా లావాదేవీలు లేవు", view_loan: "రుణాన్ని చూడండి", verify_cash: "నగదు ధృవీకరించండి", verified: "ధృవీకరించబడింది", pending: "పెండింగ్", online: "ఆన్‌లైన్", cash: "నగదు", loan_details: "రుణ వివరాలు", disbursed: "పంపిణీ చేయబడింది", loan_amount: "రుణం మొత్తం", remaining: "మిగిలినది", repayment_progress: "చెల్లింపు పురోగతి", emis_paid: "EMIలు చెల్లించబడ్డాయి", monthly_emi: "నెలవారీ EMI", next_due: "తదుపరి గడువు", all_paid: "అన్నీ చెల్లించబడ్డాయి", interest_rate: "వడ్డీ రేటు", tenure: "పదవీకాలం", months: "నెలలు", total_payable: "మొత్తం చెల్లించవలసినది", amount_paid: "చెల్లించిన మొత్తం", description: "వివరణ", loan_not_found: "రుణం కనుగొనబడలేదు",
  },
  log_activity: {
    title: "యాక్టివిటీ లాగింగ్", subtitle: "ఆర్థిక లావాదేవీలు మరియు హాజరును రికార్డ్ చేయండి", fin_entry_title: "ఆర్థిక లావాదేవీ ప్రవేశం", fin_entry_desc: "పొదుపు లేదా లోన్ చెల్లింపులను రికార్డ్ చేయండి", member_name: "సభ్యుని పేరు", select_member: "సభ్యుడిని ఎంచుకోండి", amount_rupees: "మొత్తం (₹)", transaction_type: "లావాదేవీ రకం", select_type: "రకాన్ని ఎంచుకోండి", savings: "పొదుపు", loan_repayment: "రుణ చెల్లింపు", loan_disbursed: "రుణం మంజూరు చేయబడింది", record_fin_transaction: "లావాదేవీని రికార్డ్ చేయండి", meeting_attendance: "మీటింగ్ హాజరు", meeting_attendance_desc: "సభ్యుల హాజరును లాగ్ చేయండి", meeting_date: "మీటింగ్ తేదీ", meeting_topic: "మీటింగ్ అంశం", topic_placeholder: "ఉదా., నెలవారీ సమీక్ష", present: "హాజరు", absent: "గైర్హాజరు", finalize_attendance: "హాజరును ముగించండి", recent_activity: "ఇటీవలి యాక్టివిటీ", recent_activity_desc: "గత 5 రికార్డ్ చేసిన లావాదేవీలు", no_recent: "ఇటీవలి చెల్లింపులు లేవు", monthly_round_payment: "నెలవారీ రౌండ్ చెల్లింపు", paid: "చెల్లించబడింది",
  },
  loan_approvals: {
    title: "రుణ ఆమోదాలు", no_pending: "పెండింగ్ రుణ అభ్యర్థనలు లేవు.", member_id: "సభ్యుని ID", amount: "మొత్తం", tenure: "పదవీకాలం", emi: "EMI", purpose: "ప్రయోజనం", approved: "ఆమోదించబడింది", rejected: "తిరస్కరించబడింది", approve_btn: "ఆమోదించండి", reject_btn: "తిరస్కరించండి",
  }
};
